CREATE TABLE links (
  id SERIAL PRIMARY KEY,
  published BOOLEAN NOT NULL DEFAULT 'f',
  text VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  tags VARCHAR NOT NULL,
  time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
)
